### ISSUE TITLE
Using Prebuilt binaries is deprecated

### ISSUE THREAD

**Issue by MDNSSKNGHT** [kalkioss/device_xiaomi_juice#1]
As the title tells, nowadays the use of prebuilt binaries is already deprecated, you can start by building Kernel from source, by adding these flags in [BoardConfig.mk](https://github.com/kalkioss/device_xiaomi_juice/blob/snow/BoardConfig.mk)
``
TARGET_KERNEL_SOURCE := kernel/xiaomi/juice # Clone your desired Kernel and put it.
``
``
TARGET_KERNEL_CONFIG := # This can be found either from the build script in the Kernel, or /arch/arm64/configs
``
``
BOARD_KERNEL_IMAGE_NAME := Image
``

**Comment by kalkioss** [comment]
Lol
Actually, We have oss kernels but the guy who was building ROMs for me could only use their clang fork to compile. So, I found it better for me to flash the gcc compiled kernel zip after flashing the ROM instead of using clang as compiler hehe
